### ISSUE TITLE
Pass RAM size from VC4 (in sdram.c) to ARM (via mailboxes or legacy comm channels)

### ISSUE THREAD

**Issue by alyssarosenzweig** [christinaa/rpi-open-firmware#20]

**Comment by christinaa** [comment]
Well since legacy channels are gone, I guess MBOX or writing to some high or low address is the only way now.

**Comment by alyssarosenzweig** [comment]
We _do_ have mailbox support on both ARM and the VC4, no?

**Comment by christinaa** [comment]
Passed as a structure at a fixed memory location to ARM.
