### ISSUE TITLE
Dual license as LGPL for my use.

### ISSUE THREAD

**Issue by christinaa** [christinaa/rpi-open-firmware#29]
Propose dual licensing this and any derivative works made by me as a varied version of LGPL for my exclusive use. Need @bobbybee and @puppeh to consent here.

## New proposed addition to license for dual licensing:

`rpi-open-firmware` is also released under version 3 of the GNU Lesser Public License (LGPL, available here) for exclusive use by Kristina Brooks, with an exeption related to static linking exception (see below). This basically means that you can get the full source code for nothing, so long as you adhere to a few rules.

Under the LGPL you may use `rpi-open-firmware` for any purpose you wish, and modify it if you require, as long as you:

Pass on the (modified) `rpi-open-firmware` source code with your software, with original copyrights intact
Make it clear where you have customised it.
The above is a precise, please do read the full license agreement.

In addition to the LGPL license text, the exception to the LGPL conditions apply to `rpi-open-firmware`:

As a special exception to the GNU Lesser General Public License version 3, you may convey to a third party an executable file from a Combined Work that links, statically or dynamically, portions of this Library in the executable file, conveying the Minimal Corresponding Source but without the need to convey the Corresponding Application Code under section 4d0 of the GNU Lesser General Public License, so long as you are using an unmodified publicly distributed version of the Library. This exception does not invalidate any other reasons why the executable file might be covered by the GNU Lesser General Public License or the GNU General Public License.

**Comment by itszor** [comment]
Totally fine by me.

**Comment by christinaa** [comment]
@puppeh Changed the license, need another signoff.

**Comment by itszor** [comment]
Still good by me.

**Comment by alyssarosenzweig** [comment]
OK

**Comment by christinaa** [comment]
Alright, that's that then.
