### ISSUE TITLE
Fix SDHOST support and add a Linux image loader to the second stage.

### ISSUE THREAD

**Issue by christinaa** [christinaa/rpi-open-firmware#3]
At the moment, the SDHOST driver isn't finished due to me being confused by the SD/MMC spec. This is required to load the next stage image (ie. Uboot or Linux) into RAM and execute it. I don't have the time to look into this at the moment but if anyone with SD/MMC experience can help out, that would be greatly appreciated since it would actually allow booting a minimal Linux distro without any blobs.

**Comment by SunilMohanAdapa** [comment]
We, at the FreedomBox project, are waiting quite eagerly to build fully free images for RPi2/3. We have already tested out Debian's kernel and u-boot to support all the necessary parts of RPi2/3.  This would be the last piece.

Thank you for your work so far. I wish I had the expertise and time to assist. Hope someone turns up.

**Comment by christinaa** [comment]
Fixed SD card issues today as well as making the boot partition mountable under the ARM part of the bootloader. Only thing left is loading and executing a second stage bootloader like u-boot or LK. The problem is that at this point, Linux and u-boot heavily rely on firmware for stuff like power management etc. Just being able to load a Linux image isn't going to make it do a lot of useful stuff, with some patches it could probably boot up with USB/UART/GPIO support. HDMI/HVS/PV would probably be tricker and it's pretty crappy to have a rPi that can't show anything on screen.

**Comment by SunilMohanAdapa** [comment]
On 06/08/2016 08:03 AM, Kristina Brooks wrote:

> Fixed SD card issues today as well as making the boot partition 
> mountable under the ARM part of the bootloader.

Awesome!

> Only thing left is loading and executing a second stage bootloader 
> like u-boot or LK. The problem is that at this point, Linux and 
> u-boot heavily rely on firmware for stuff like power management etc. 
> Just being able to load a Linux image isn't going to make it do a lot
> of useful stuff, with some patches it could probably boot up with 
> USB/UART/GPIO support.

Oh!

> HDMI/HVS/PV would probably be tricker and it's pretty crappy to have
>  a rPi that can't show anything on screen.

For FreedomBox, and presumably other use cases, this is not an issue.
It serves as personal server and Wi-Fi router at home.  Most of the
devices supported actually run headless.  Even the setup process is well
tuned to not require any display.  For development purposes we use
USB-serial connectors.

## 

Sunil
