### ISSUE TITLE
Backport to iPod (5-5.5g)

### ISSUE THREAD

**Issue by snshn** [christinaa/rpi-open-firmware#32]
Would it require more effort to port this firmware to implement support for BCM2722 under Rockbox/iPodLinux to utilize the hardware acceleration for iPod Video rather than to write a from-scratch driver for that chip?

**Comment by alyssarosenzweig** [comment]
> Would it require more effort to port this firmware to implement support for BCM2722 under Rockbox/iPodLinux to utilize the hardware acceleration for iPod Video rather than to write a from-scratch driver for that chip?

The firmware is primarily concerned with peripheral bringup as opposed
to graphics at the moment. So no, I don't believe our code will be
useful for the older chipset. That being said, you might have luck
looking at the free graphics stack (released by Broadcom!).

**Comment by snshn** [comment]
Thank you.

**Comment by alyssarosenzweig** [comment]
Sure :-)
